In [2]:
import pandas as pd
ldf = pd.read_csv('archive/listings_cleaned_v2.csv', sep=',', encoding='utf-8')
wdf = pd.read_csv('archive/weekly_prices_v2.csv', sep=',', encoding='utf-8')
cdf = pd.read_csv('archive/calendar_months_seasons_v2.csv', sep=',', encoding='utf-8')
ccdf = pd.read_csv('archive/calendar_cleaned_v2.csv', sep=',', encoding='utf-8')

In [70]:
ldf.groupby(['neighbourhood_cleansed', 'room_type']).agg({'room_type':'count'})

                                           room_type
neighbourhood_cleansed    room_type
Amager Vest               Entire home/apt        956
                          Private room           166
Amager Øst                Entire home/apt        766
                          Private room           119
Bispebjerg                Entire home/apt        508
                          Private room            89
Brønshøj-Husum            Entire home/apt        229
                          Private room            69
Frederiksberg             Entire home/apt       1063
                          Private room           130
Indre By                  Entire home/apt       1716
                          Private room           143
Nørrebro                  Entire home/apt       1750
                          Private room           172
Valby                     Entire home/apt        465
                          Private room            91
Vanløse                   Entire home/apt        275
                          Private room            45
Vesterbro-Kongens Enghave Entire home/apt       1769
                          Private room           222
Østerbro                  Entire home/apt       1184
                          Private room           137

In [73]:
ldf.groupby(['neighbourhood_cleansed', 'room_type']).size().reset_index(name='count')

       neighbourhood_cleansed        room_type  count
0                 Amager Vest  Entire home/apt    956
1                 Amager Vest     Private room    166
2                  Amager Øst  Entire home/apt    766
3                  Amager Øst     Private room    119
4                  Bispebjerg  Entire home/apt    508
5                  Bispebjerg     Private room     89
6              Brønshøj-Husum  Entire home/apt    229
7              Brønshøj-Husum     Private room     69
8               Frederiksberg  Entire home/apt   1063
9               Frederiksberg     Private room    130
10                   Indre By  Entire home/apt   1716
11                   Indre By     Private room    143
12                   Nørrebro  Entire home/apt   1750
13                   Nørrebro     Private room    172
14                      Valby  Entire home/apt    465
15                      Valby     Private room     91
16                    Vanløse  Entire home/apt    275
17                    Vanløse     Private room     45
18  Vesterbro-Kongens Enghave  Entire home/apt   1769
19  Vesterbro-Kongens Enghave     Private room    222
20                   Østerbro  Entire home/apt   1184
21                   Østerbro     Private room    137

In [65]:
ldf = ldf[ldf['room_type'] != 'Shared room']

In [3]:
ldf

,id,neighbourhood_cleansed,latitude,longitude,room_type,accommodates,bedrooms,beds,price,bathrooms
0,6983,Nørrebro,55.68641,12.54741,Entire home/apt,2,1.0,1,877.0,1.0
1,26057,Indre By,55.69307,12.57649,Entire home/apt,6,4.0,4,2400.0,1.5
2,26473,Indre By,55.67602,12.57540,Entire home/apt,11,5.0,5,3350.0,2.0
3,29118,Vesterbro-Kongens Enghave,55.67023,12.55504,Entire home/apt,2,1.0,1,725.0,1.0
4,670820,Indre By,55.69001,12.57315,Entire home/apt,4,1.0,2,1116.0,1.0
...,...,...,...,...,...,...,...,...,...,...
12059,35292340,Brønshøj-Husum,55.72588,12.48023,Entire home/apt,4,3.0,3,750.0,1.0
12060,591033498117946366,Valby,55.65762,12.47260,Entire home/apt,4,2.0,2,1100.0,1.0
12061,9872599,Bispebjerg,55.73184,12.52648,Entire home/apt,7,5.0,5,1195.0,2.0
12062,595224605480025818,Brønshøj-Husum,55.73815,12.49684,Entire home/apt,4,2.0,4,1499.0,1.0
12063,4806059,Bispebjerg,55.73038,12.54425,Entire home/apt,8,4.0,8,1400.0,1.5